# Generated by Django 2.2.2 on 2019-06-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20190625_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('money', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'bank balance',
                'verbose_name_plural': 'bank balances',
                'ordering': ('date',),
            },
        ),
    ]
