# The base docker-compose file.
# During local development this file will be merged with
# docker-compose.override.yml, providing config only used
# in testing and development. During production it will be
# merged with docker-compose.prod.yml instead.
version: '3'

services:
  db:
    image: postgres:10.1-alpine
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: backend
    volumes:
      - backend_static:/backend/static
      - backend_media:/backend/media
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      args:
        - REACT_APP_BASE_URL=/api
    environment:
      - REACT_APP_BASE_URL=/api
    networks:
      - nginx_network
  nginx:
    image: nginx
    environment:
      - host=liquidator
    ports:
      - ${NGINX_PORT:-8000}:80
    volumes:
      - backend_static:/backend/static:ro
      - backend_media:/backend/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nginx_network

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data:
  backend_static:
  backend_media:
