version: '3'

services:
  backend:
    #command: python manage.py runserver
    command: gunicorn --chdir liquidator --bind :8000 liquidator.wsgi:application
    volumes:
      - ./backend:/backend/code
  frontend:
    command: yarn start
    volumes:
      - ./frontend:/frontend/code
    environment:
      - CI
  nginx:
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
