version: '3'

services:
  backend:
    command: gunicorn --chdir liquidator --bind :8000 liquidator.wsgi:application
    build:
      args:
        - PROD=true
        - DJANGO_SECRET_KEY
    environment:
      - PROD=true
      - DJANGO_SECRET_KEY
  frontend:
    command: cp -r /frontend/build/ /frontend/static/
    user: root
    volumes:
      - frontend_static:/frontend/static/build
  nginx:
    volumes:
      - ./config/prod/nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend_static:/frontend/static:ro

volumes:
  frontend_static:
