# Generated by Django 2.2.2 on 2019-06-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190621_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='orgNr',
            new_name='org_nr',
        ),
    ]
