# Generated by Django 2.2.4 on 2019-08-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190625_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='The name of the company', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='org_nr',
            field=models.CharField(help_text='The organization identifier', max_length=20, unique=True),
        ),
    ]
