version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            make build
            make up
            make test
            make down
