# Generated by Django 2.2.4 on 2019-08-27 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20190621_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(help_text='The companies the user has access to', related_name='users', through='custom_auth.UserCompanyThrough', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The users email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usercompanythrough',
            name='company',
            field=models.ForeignKey(help_text='The company', on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='usercompanythrough',
            name='role',
            field=models.CharField(choices=[('RE', 'Reporter'), ('US', 'User'), ('OW', 'Owner')], default='US', help_text='The users role in the company', max_length=2),
        ),
        migrations.AlterField(
            model_name='usercompanythrough',
            name='user',
            field=models.ForeignKey(help_text='The user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
