# Generated by Django 2.2.2 on 2019-06-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190621_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='transaction.RecurringTransaction'),
        ),
    ]
