# Generated by Django 2.2.2 on 2019-07-19 15:16

from django.db import migrations

from transaction.models import RecurringTransaction as RT


def set_interval(apps, schema_editor):
    RecurringTransaction = apps.get_model('transaction', 'RecurringTransaction')

    for recurring in RecurringTransaction.objects.all():
        if recurring.month_delta > 0:
            recurring.interval_type = RT.MONTH
            recurring.interval = recurring.month_delta
        elif recurring.day_delta > 0:
            recurring.interval_type = RT.DAY
            recurring.interval = recurring.day_delta

        recurring.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190719_1715'),
    ]

    operations = [
        migrations.RunPython(set_interval),
    ]
