# Generated by Django 2.2.2 on 2019-06-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20190621_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('money', models.IntegerField()),
                ('type', models.CharField(choices=[('IN', 'income'), ('EX', 'expense')], max_length=2)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='company.Company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
