# Generated by Django 2.2.2 on 2019-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190625_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='interval',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='interval_type',
            field=models.CharField(choices=[('DA', 'day'), ('MO', 'month')], default='DA', max_length=2),
            preserve_default=False,
        ),
    ]
