# Generated by Django 2.2.2 on 2019-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190719_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
